### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/technical.buildingsmart.org#2]
I can't seem to be able to access this file. Is there an alternative location somewhere?

https://github.com/buildingSMART/technical.buildingsmart.org/blob/923deeb0ea8ce72c1da7e3c3f0485ef79fabc617/IFC-GUID.md?plain=1#L21

**Comment by berlotti** [comment]
ifcdoc has been discontinued by buildingSMART
website page has been updated accordingly
Thanks for the notice!
